const initialData = [
  {
    type: 'rectangle',
    version: 12,
    versionNonce: 131106491,
    index: 'a0',
    isDeleted: false,
    id: '5zcOdyvGFL_ChAm3XJwbM',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    angle: 0,
    x: 308,
    y: 191,
    strokeColor: '#1e1e1e',
    backgroundColor: 'transparent',
    width: 226,
    height: 221,
    seed: 1874946701,
    groupIds: [],
    frameId: null,
    roundness: {
      type: 3
    },
    boundElements: [],
    updated: 1712943688514,
    link: null,
    locked: false
  },
  {
    type: 'ellipse',
    version: 24,
    versionNonce: 7116405,
    index: 'a1',
    isDeleted: false,
    id: 'AZYS3fEHGZo1xUQsMA2ST',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    angle: 0,
    x: 391,
    y: 471,
    strokeColor: '#1e1e1e',
    backgroundColor: 'transparent',
    width: 169,
    height: 166,
    seed: 1310768301,
    groupIds: [],
    frameId: null,
    roundness: {
      type: 2
    },
    boundElements: [],
    updated: 1712943688514,
    link: null,
    locked: false
  },
  {
    id: '9ZzWzWPkndF1uBHjAL4TG',
    type: 'line',
    x: 575,
    y: 169,
    width: 79,
    height: 199,
    angle: 0,
    strokeColor: '#1e1e1e',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    groupIds: [],
    frameId: null,
    index: 'a2',
    roundness: {
      type: 2
    },
    seed: 1173840502,
    version: 15,
    versionNonce: 703627958,
    isDeleted: false,
    boundElements: null,
    updated: 1712970065193,
    link: null,
    locked: false,
    points: [
      [0, 0],
      [79, 199]
    ],
    lastCommittedPoint: null,
    startBinding: null,
    endBinding: null,
    startArrowhead: null,
    endArrowhead: null
  },
  {
    id: 'uF-2zo6jbMJDT0yvEzJf7',
    type: 'diamond',
    x: 619,
    y: 437,
    width: 172,
    height: 181,
    angle: 0,
    strokeColor: '#1e1e1e',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    groupIds: [],
    frameId: null,
    index: 'a3',
    roundness: {
      type: 2
    },
    seed: 427473910,
    version: 34,
    versionNonce: 1403092586,
    isDeleted: false,
    boundElements: null,
    updated: 1712970071782,
    link: null,
    locked: false
  },
  {
    id: 'SV8-RMIdVkglxVimUmxM7',
    type: 'arrow',
    x: 628,
    y: 626,
    width: 88,
    height: 126,
    angle: 0,
    strokeColor: '#1e1e1e',
    backgroundColor: 'transparent',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    groupIds: [],
    frameId: null,
    index: 'a4',
    roundness: {
      type: 2
    },
    seed: 544874794,
    version: 29,
    versionNonce: 1564564330,
    isDeleted: false,
    boundElements: null,
    updated: 1712970084158,
    link: null,
    locked: false,
    points: [
      [0, 0],
      [88, 126]
    ],
    lastCommittedPoint: null,
    startBinding: null,
    endBinding: null,
    startArrowhead: null,
    endArrowhead: 'arrow'
  }
];

export default initialData;
