const initialData = [
  {
    type: 'rectangle',
    version: 12,
    versionNonce: 131106491,
    isDeleted: false,
    id: '5zcOdyvGFL_ChAm3XJwbM',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    angle: 0,
    x: 308,
    y: 191,
    strokeColor: '#1e1e1e',
    backgroundColor: 'transparent',
    width: 226,
    height: 221,
    seed: 1874946701,
    groupIds: [],
    frameId: null,
    roundness: { type: 3 },
    boundElements: [],
    updated: 1712943688514,
    link: null,
    locked: false,
    index: 'a0'
  },
  {
    type: 'ellipse',
    version: 24,
    versionNonce: 7116405,
    isDeleted: false,
    id: 'AZYS3fEHGZo1xUQsMA2ST',
    fillStyle: 'solid',
    strokeWidth: 2,
    strokeStyle: 'solid',
    roughness: 1,
    opacity: 100,
    angle: 0,
    x: 391,
    y: 471,
    strokeColor: '#1e1e1e',
    backgroundColor: 'transparent',
    width: 169,
    height: 166,
    seed: 1310768301,
    groupIds: [],
    frameId: null,
    roundness: { type: 2 },
    boundElements: [],
    updated: 1712943688514,
    link: null,
    locked: false,
    index: 'a1'
  }
];

export default initialData;
